-- ============================================================
-- ESQUEMA DO BANCO DE DADOS SUPABASE - PULMÃO DE CAIXAS BOTICÁRIO
-- Executar este script no SQL Editor do Supabase Dashboard
-- ============================================================

-- 1. TABELA DE PRODUTOS
CREATE TABLE IF NOT EXISTS public.produtos (
    codigo TEXT PRIMARY KEY,
    descricao TEXT NOT NULL,
    cx_por_palete INTEGER DEFAULT 0,
    criado_em TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABELA DE POSIÇÕES DO PULMÃO (2.646 Posições)
CREATE TABLE IF NOT EXISTS public.posicoes (
    id TEXT PRIMARY KEY, -- Exemplo: R5-01-B-P01
    rua INTEGER NOT NULL,
    rack TEXT NOT NULL,
    coluna TEXT NOT NULL,
    nivel INTEGER NOT NULL,
    disponivel BOOLEAN DEFAULT TRUE,
    criado_em TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABELA DE ALOCAÇÕES / CAIXAS NAS POSIÇÕES
CREATE TABLE IF NOT EXISTS public.caixas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    posicao_id TEXT REFERENCES public.posicoes(id) ON DELETE CASCADE,
    codigo_produto TEXT REFERENCES public.produtos(codigo),
    descricao TEXT,
    cx_por_palete INTEGER DEFAULT 0,
    cx_no_palete INTEGER DEFAULT 0,
    un_sobra INTEGER DEFAULT 0,
    validade TEXT,
    alocado_em TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABELA DE HISTÓRICO DE MOVIMENTAÇÕES
CREATE TABLE IF NOT EXISTS public.movimentacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora TIMESTAMPTZ DEFAULT NOW(),
    tipo TEXT NOT NULL, -- 'ENTRADA', 'SAIDA', 'TRANSFERENCIA', 'LIMPEZA'
    sku TEXT,
    descricao TEXT,
    qtd INTEGER DEFAULT 0,
    origem TEXT,
    destino TEXT,
    usuario TEXT DEFAULT 'Operador'
);

-- 5. TABELA DE SOBRAS / FRACIONADOS
CREATE TABLE IF NOT EXISTS public.sobras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    posicao_id TEXT REFERENCES public.posicoes(id) ON DELETE CASCADE,
    codigo TEXT NOT NULL,
    quantidade INTEGER DEFAULT 0,
    validade TEXT,
    atualizado_em TIMESTAMPTZ DEFAULT NOW()
);

-- HABILITAR RLS (Row Level Security) COM ACESSO PÚBLICO (Leitura/Escrita)
ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posicoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.caixas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movimentacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sobras ENABLE ROW LEVEL SECURITY;

-- Políticas de acesso livre para uso local/operacional
CREATE POLICY "Acesso Total Produtos" ON public.produtos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso Total Posicoes" ON public.posicoes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso Total Caixas" ON public.caixas FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso Total Movimentacoes" ON public.movimentacoes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso Total Sobras" ON public.sobras FOR ALL USING (true) WITH CHECK (true);

-- Índices para otimização de busca rápida no mapa e no estoque
CREATE INDEX IF NOT EXISTS idx_posicoes_rua ON public.posicoes(rua);
CREATE INDEX IF NOT EXISTS idx_caixas_posicao ON public.caixas(posicao_id);
CREATE INDEX IF NOT EXISTS idx_caixas_codigo ON public.caixas(codigo_produto);
CREATE INDEX IF NOT EXISTS idx_movimentacoes_sku ON public.movimentacoes(sku);
